### ISSUE TITLE
Повышение онлайна

### ISSUE THREAD

**Issue by Valtosin** [frosty-dev/white-dream-main#1]
Методом простого анализа тыков было выявлено то, что 95% игроков SS13 воспринимают первичную информацию и считают её наиболее верной, чем оказывается на деле.

Следствие, можно попробовать использовать концепт СММ, который используется на многих проектах в ру-секторе, в подавляющем числе там, где больше всего онлайна.

Вроде это ещё называется концептом "пиздабола", но нам терять нечего.

Реквест создан для редпиллинга бумажных жоп, так что жду ваши ответы.

**Comment by n0rm4ld3f4ult** [comment]
проблема - разработ_очка кулдена, выпилить гост и суицид, блять кулден ты серьёзно??? иди на бей
