### ISSUE TITLE
[IDEA] Добавить на Омегу крайне важные и нужные предметы

### ISSUE THREAD

**Issue by Rubikoid** [frosty-dev/white-dream-main#26]
На омеге с начала раунда нет некоторых крайне полезных предметов. Например, карта капитана не спавнится, а в fire safety closet нету долбанных монтировок.

**Comment by Valtosin** [comment]
https://github.com/frosty-dev/white-dream-main/commit/436d764a9312a65633b8a0b57da0d074a65952d4
Капитанская карта теперь всегда будет спауниться в шкафчике капитана.

https://github.com/frosty-dev/white-dream-main/commit/726d1511c00dc6b3eddff9a46e5890c1e7c16235
Теперь в каждом шкафчике пожарника есть монтировка.
