### ISSUE TITLE
[BUG] Призраки пролетают через окна только в одну сторону

### ISSUE THREAD

**Issue by Rubikoid** [frosty-dev/white-dream-main#27]
## Как повторить?

Призраки пролетают через плоские окна только в одну сторону, т.е. снаружи-->внутрь. В обратную сторону уже не могут. То же касается и плоских дверей, в одну сторону призрак пролетает сразу, заодно инициируя открытие двери, а в другую - не может пролететь, пока дверь не откроется.

На скрине: 
зеленая стрелка - пролетают нормально
красная стрелка - не могут пролететь.
![Annotation 2020-01-12 235510](https://user-images.githubusercontent.com/5082689/72225517-3db7a200-3597-11ea-87e3-a74964820889.png)

**Comment by Valtosin** [comment]
https://github.com/frosty-dev/white-dream-main/commit/53dcc155613327b3f187c25b30142daaf72da9a7
Теперь госты могут делать всё как и раньше.
