### ISSUE TITLE
[BUG] Nanite remote тулы сломаны

### ISSUE THREAD

**Issue by Rubikoid** [frosty-dev/white-dream-main#28]
## Как повторить?
Nanite communication remote и Nanite remote control сломаны - как их не тыкать, применение кода не происходит.
Реплай:
1. Поставить любую нанитовую программу, например, Host scan, прописав в ней ненулевой код триггера.
2. Для сравнения, поставить программу Dermal Button и в ней прописать тот же код.
3. Взять communication remote/remote control и попробовать активировать этот код в любом режиме.
4. Активировать код кнопкой на теле.
5. Тулза не работает, кнопка работает.

**Comment by Valtosin** [comment]
Проблема была вызвана кривыми дефайнами в коде.
Пофикшено в https://github.com/frosty-dev/white-dream-main/commit/ede5c8d3f28033376479b15c9913a7fe0544a472
