### ISSUE TITLE
[IDEA]

### ISSUE THREAD

**Issue by Traveller-D** [frosty-dev/white-dream-main#57]
К карте Валтосина
- У вирусолога нет места для работы (на шахтерке может?) 
- Место под крио в медбее. 
- Ассистенты не имеют склада с инструментами (если захочешь) 
- парилка в кабинете атмостеха: пар дует в стену, можно ли повернуть его в сторону техов? 
- библиотека: комп, который выдает книги, смотрит жопой к тому, кто будет за ним работать. 
- церква: при похоронах гробы врезаются в голодек, что-то нужно с космосом сделать 
- космос в приемной станции не телепортирует игроков в открытый космос ( а зря) 
- нет комнаты для актеров (мима и клована )

**Comment by Valtosin** [comment]
Вирусология теперь на морозной планете.
Крио не добавлял пока (душ есть хуле).
Склад с инструментами и автолатом теперь на морозной планете.
Парилка теперь убрана в техи и повёрнута в другую сторону.
Компьютер в библиотеке теперь не смотрит жопой.
Опенспейсы на морозной планете теперь выкидывают всё живое и не живое в космос.
Комната для мима/клоуна это космос.

**Comment by Valtosin** [comment]
Космос на планете теперь выкидывает на поверхность планеты и ломает лицо. Остальное из списка не менял.
