### ISSUE TITLE
Надо бы спрайтов

### ISSUE THREAD

**Issue by Valtosin** [frosty-dev/white-dream-main#58]
Хочу спрайтера. Пиздец.

**Comment by RedFoxIV** [comment]
готов спрайтить в мс пеинт за хлеб
мои тарифы:
легаси классик: 3 руб/пиксель, лимит 250 пикселей в месяц
эконом экспанд: 1 руб 10 коп/пиксель, лимит 100 пикселей в месяц + 2 руб/пиксель после исчерпания лимита
безлимит: 2 руб/пиксель + 100 руб минимальный ежемесячный платёж

_примечание: руб. употребляется в контексте "хлеб"_
