### ISSUE TITLE
[BUG] Ченжлинги умирают навсегда если им отрубить голову

### ISSUE THREAD

**Issue by nullAdept** [frosty-dev/white-dream-main#86]
## ID Раунда: не применимо
Эту хуйню уже очень давно не фиксят на тг и наверное было бы неплохо это починить тут...

## Как повторить?

1. Взять генокрада
2. Убить генокрада
3. Отрубить ему голову

**Comment by Valtosin** [comment]
По идее какой-то фикс сделал, но надо проверить будет.

**Comment by Valtosin** [comment]
Примерно ковырял код, пытался исправить, но пока без результатов. Оригинальная иссуя тут: https://github.com/tgstation/tgstation/issues/51408

**Comment by nullAdept** [comment]
Там их штуки 4 было вообще...

**Comment by Valtosin** [comment]
Потому что не могут пофиксить после какого-то коммита с изменением в уклон возможности ревайвать дефибами и прочей хуйнёй (на деле и так работало нормально).

**Comment by nullAdept** [comment]
Ебаные тгшники, лишь бы поломать что-то..

**Comment by Valtosin** [comment]
О, ну там кстати фиксили уже это давно. Попробую применить фикс.

**Comment by Valtosin** [comment]
Хз, походу я вернул как было щас https://github.com/frosty-dev/white-dream-main/commit/b341fc3446450e25ae1eb73508c99ba631155d87
Там пиздец говнокода и надо разбираться теперь

**Comment by nullAdept** [comment]
Возможно это как-то связано с харсом?

**Comment by nullAdept** [comment]
С ним тоже баг есть, типо если взорвать им себе голову и сменить расу, то у тебя отрастут глаза, уши и рот, а голова не отрастёт...

**Comment by Valtosin** [comment]
пофикшено https://github.com/tgstation/tgstation/pull/52292
