### ISSUE TITLE
Попиксельное движение, невидимые широкие стулья и застревание в углах. [BUG]

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white-dream-main#90]
## Как повторить?
**### Невидимые широкие стулья** 
1. Подходим к стулу.
2. Стать по середине стула.
3. Чутка отойти.
4. Сесть на него.
![Screenshot_43](https://user-images.githubusercontent.com/44509388/89906695-61f26480-dbf4-11ea-870e-6b0cd3d0c07b.png)

### **Застревание в углах**
1. Найти моба;
2. Тащить его к углу.
3. подходим к углу и под прямым углом проходим.
4. Он застревает, как и мы.

![Screenshot_42](https://user-images.githubusercontent.com/44509388/89906627-4ab37700-dbf4-11ea-8fab-720872c53bf0.png)
Erring

**Comment by Valtosin** [comment]
Пофикшено выпиливанием попикселя.
